/**
 * Vendored from `@openai/apps-sdk-ui` 0.2.2 (MIT, Copyright 2025 OpenAI) —
 * `dist/es/components/Icon/svg/ArrowDown.js`. Licence in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`). Do not edit by hand.
 */
import type { SVGProps } from "react";

const ArrowDown = (props: SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" data-icon="arrow-down" aria-hidden="true" {...props}>
    <path fillRule="evenodd" d="M12.707 18.707a1 1 0 0 1-1.414 0l-5-5a1 1 0 1 1 1.414-1.414L11 15.586V6a1 1 0 1 1 2 0v9.586l3.293-3.293a1 1 0 0 1 1.414 1.414l-5 5Z" clipRule="evenodd" />
  </svg>
);

export default ArrowDown;
