/**
 * Vendored from `@openai/apps-sdk-ui` 0.2.2 (MIT, Copyright 2025 OpenAI) —
 * `dist/es/components/Icon/svg/Check.js`. Licence in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`). Do not edit by hand.
 */
import type { SVGProps } from "react";

const Check = (props: SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" data-icon="check" aria-hidden="true" {...props}>
    <path fillRule="evenodd" d="M18.063 5.674a1 1 0 0 1 .263 1.39l-7.5 11a1 1 0 0 1-1.533.143l-4.5-4.5a1 1 0 1 1 1.414-1.414l3.647 3.647 6.82-10.003a1 1 0 0 1 1.39-.263Z" clipRule="evenodd" />
  </svg>
);

export default Check;
