/**
 * Vendored from `@openai/apps-sdk-ui` 0.2.2 (MIT, Copyright 2025 OpenAI) —
 * `dist/es/components/Icon/svg/ChevronRight.js`. Licence in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`). Do not edit by hand.
 */
import type { SVGProps } from "react";

const ChevronRight = (props: SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" data-icon="chevron-right" aria-hidden="true" {...props}>
    <path fillRule="evenodd" d="M8.293 4.293a1 1 0 0 1 1.414 0l7 7a1 1 0 0 1 0 1.414l-7 7a1 1 0 0 1-1.414-1.414L14.586 12 8.293 5.707a1 1 0 0 1 0-1.414Z" clipRule="evenodd" />
  </svg>
);

export default ChevronRight;
