/**
 * Vendored from `@openai/apps-sdk-ui` 0.2.2 (MIT, Copyright 2025 OpenAI) —
 * `dist/es/components/Icon/svg/CollapseSmall.js`. Licence in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`). Do not edit by hand.
 */
import type { SVGProps } from "react";

const CollapseSmall = (props: SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" data-icon="collapse-small" aria-hidden="true" {...props}>
    <path d="M5 14a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0v-3H6a1 1 0 0 1-1-1Zm9-9a1 1 0 0 1 1 1v3h3a1 1 0 1 1 0 2h-4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z" />
  </svg>
);

export default CollapseSmall;
