/**
 * Vendored from `@openai/apps-sdk-ui` 0.2.2 (MIT, Copyright 2025 OpenAI) —
 * `dist/es/components/Icon/svg/ExternalLink.js`. Licence in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`). Do not edit by hand.
 */
import type { SVGProps } from "react";

const ExternalLink = (props: SVGProps<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" data-icon="external-link" aria-hidden="true" {...props}>
    <path fillRule="evenodd" d="M15 5a1 1 0 1 1 0-2h5a1 1 0 0 1 1 1v5a1 1 0 1 1-2 0V6.414l-5.293 5.293a1 1 0 0 1-1.414-1.414L17.586 5H15ZM4 7a3 3 0 0 1 3-3h3a1 1 0 1 1 0 2H7a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-3a1 1 0 1 1 2 0v3a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V7Z" clipRule="evenodd" />
  </svg>
);

export default ExternalLink;
