/**
 * The app's icon set: 75 glyphs vendored from `@openai/apps-sdk-ui` 0.2.2
 * (MIT, Copyright 2025 OpenAI). Licence and attribution in `src/icons/LICENSE.md`.
 *
 * Generated by `scripts/vendor-icons.mjs` (`npm run vendor:icons`) from `src/icons/manifest.json`.
 * Do not edit by hand — add the name to the manifest and re-run instead.
 *
 * Every icon renders at `1em` and inherits `currentColor`, so size it with a `size-*` class, a
 * `font-size`, or explicit `width`/`height`. Each carries `data-icon="<kebab-name>"` on its root,
 * which is what tests should target, and `aria-hidden="true"`, since a glyph is decorative unless the
 * call site says otherwise — both sit before `{...props}`, so a call site can override either.
 */
import type { ComponentType, SVGProps } from "react";

/** Any icon in this set, for props and lookup tables that hold one. */
export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export { default as Archive } from "./Archive";
export { default as ArrowDown } from "./ArrowDown";
export { default as ArrowLeft } from "./ArrowLeft";
export { default as ArrowRight } from "./ArrowRight";
export { default as ArrowRotateCcw } from "./ArrowRotateCcw";
export { default as ArrowRotateCw } from "./ArrowRotateCw";
export { default as ArrowUp } from "./ArrowUp";
export { default as ArrowUpRight } from "./ArrowUpRight";
export { default as Bell } from "./Bell";
export { default as Bolt } from "./Bolt";
export { default as BookOpen } from "./BookOpen";
export { default as Branch } from "./Branch";
export { default as BranchAlt } from "./BranchAlt";
export { default as Bug } from "./Bug";
export { default as Chat } from "./Chat";
export { default as Check } from "./Check";
export { default as ChevronDown } from "./ChevronDown";
export { default as ChevronRight } from "./ChevronRight";
export { default as ChevronSmallDown } from "./ChevronSmallDown";
export { default as ChevronSmallRight } from "./ChevronSmallRight";
export { default as ChevronUp } from "./ChevronUp";
export { default as Code } from "./Code";
export { default as CollapseSmall } from "./CollapseSmall";
export { default as Compare } from "./Compare";
export { default as Copy } from "./Copy";
export { default as Desktop } from "./Desktop";
export { default as DotsHorizontal } from "./DotsHorizontal";
export { default as Edit } from "./Edit";
export { default as ExclamationMarkCircle } from "./ExclamationMarkCircle";
export { default as Expand } from "./Expand";
export { default as ExternalLink } from "./ExternalLink";
export { default as File } from "./File";
export { default as FileDocument } from "./FileDocument";
export { default as Filter } from "./Filter";
export { default as Folder } from "./Folder";
export { default as FolderOpen } from "./FolderOpen";
export { default as FolderPlusAdd } from "./FolderPlusAdd";
export { default as Folders } from "./Folders";
export { default as Globe } from "./Globe";
export { default as HandRaised } from "./HandRaised";
export { default as Loop } from "./Loop";
export { default as Menu } from "./Menu";
export { default as Minus } from "./Minus";
export { default as Nodes } from "./Nodes";
export { default as Notebook } from "./Notebook";
export { default as Notepad } from "./Notepad";
export { default as Pencil } from "./Pencil";
export { default as Pin } from "./Pin";
export { default as PinFilled } from "./PinFilled";
export { default as Plus } from "./Plus";
export { default as PlusCircle } from "./PlusCircle";
export { default as Robot } from "./Robot";
export { default as Search } from "./Search";
export { default as Settings } from "./Settings";
export { default as SettingsCog } from "./SettingsCog";
export { default as SettingsSlider } from "./SettingsSlider";
export { default as ShieldCheck } from "./ShieldCheck";
export { default as Sidebar } from "./Sidebar";
export { default as SidebarRight } from "./SidebarRight";
export { default as Sparkle } from "./Sparkle";
export { default as Sun } from "./Sun";
export { default as Tag } from "./Tag";
export { default as Telescope } from "./Telescope";
export { default as Terminal } from "./Terminal";
export { default as TerminalLg } from "./TerminalLg";
export { default as ThumbDown } from "./ThumbDown";
export { default as ThumbUp } from "./ThumbUp";
export { default as Tools } from "./Tools";
export { default as Trash } from "./Trash";
export { default as Unarchive } from "./Unarchive";
export { default as Undo } from "./Undo";
export { default as User } from "./User";
export { default as Users } from "./Users";
export { default as Warning } from "./Warning";
export { default as X } from "./X";
