// SPDX-License-Identifier: Apache-2.0
/**
 * Generate the two attribution surfaces ruling 47 requires.
 *
 *   THIRD-PARTY.md            for the repository and the plugin directory
 *   src/generated/licenses.ts for `brigadier licenses`, inside the binary
 *
 * Both come from the same walk of what is actually shipped, which is the whole
 * point: attribution that is typed by hand drifts from the artifact silently,
 * and a THIRD-PARTY missing a newly-bundled dependency looks exactly like a
 * correct one.
 *
 * The in-binary surface is the load-bearing one. Apache-2.0 §4(a) is owed to
 * whoever RECEIVES the work, and under ruling 26 the delivery is often a bare
 * binary — a Homebrew tap, `curl | sh`, a plugin directory — with no repository
 * anywhere near it. A file that lives only in the repo does not discharge it.
 *
 *   bun run licenses            regenerate
 *   bun run licenses --check    fail if the committed output is stale
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT, allComponents, isAllowed, type Component } from "./inventory.ts";

const APACHE_TEXT = readFileSync(join(REPO_ROOT, "LICENSE"), "utf8").trimEnd();

function renderMarkdown(components: Component[]): string {
  const lines: string[] = [];
  lines.push("# Third-party components");
  lines.push("");
  lines.push("<!-- GENERATED by `bun run licenses` — do not edit. Ruling 47. -->");
  lines.push("");
  lines.push(
    "brigadier ships as a single compiled binary, so every component below is **inside the artifact you",
    "received**, not merely a build-time dependency. This file is generated from what is actually",
    "bundled rather than maintained by hand, because hand-written attribution drifts from the binary",
    "silently.",
  );
  lines.push("");
  lines.push("The same content is reachable from the binary itself with `brigadier licenses`, which is the");
  lines.push("surface that matters when brigadier arrives without this repository beside it.");
  lines.push("");
  lines.push("| component | version | licence | why it is in the binary |");
  lines.push("| --- | --- | --- | --- |");
  for (const c of components) {
    lines.push(`| \`${c.name}\` | ${c.version} | ${c.license} | ${c.reason} |`);
  }
  lines.push("");

  const lgpl = components.find((c) => c.licenseText.includes("LGPL"));
  if (lgpl) {
    lines.push("## Statically linked LGPL components, and how to relink");
    lines.push("");
    lines.push(
      "`" + lgpl.name + "` statically links **JavaScriptCore/WebKit (LGPL-2)** and **tinycc (LGPL-2.1)**.",
      "LGPL-2 asks that a recipient be able to modify those libraries and relink the application. brigadier",
      "is built by `bun build --compile` from its own published source, so the relink path is: rebuild Bun",
      "against your modified WebKit (upstream documents this at <https://github.com/oven-sh/webkit>), then",
      "rebuild brigadier with `bun run build` using that Bun.",
    );
    lines.push("");
  }

  lines.push("## Full licence texts");
  lines.push("");
  for (const c of components) {
    lines.push(`### ${c.name} ${c.version} — ${c.license}`);
    lines.push("");
    if (c.copyright) lines.push(`${c.copyright}`, "");
    lines.push("```");
    lines.push(c.licenseText || "(the component ships no licence file; the declared licence is above)");
    lines.push("```");
    lines.push("");
  }

  lines.push("## brigadier's own licence");
  lines.push("");
  lines.push("Apache-2.0. See `LICENSE`.");
  lines.push("");
  return lines.join("\n");
}

function renderTypeScript(components: Component[]): string {
  const payload = {
    self: {
      name: "brigadier",
      license: "Apache-2.0",
      copyright: "Copyright 2026 Stephen Golban",
    },
    components: components.map((c) => ({
      name: c.name,
      version: c.version,
      license: c.license,
      copyright: c.copyright ?? null,
      reason: c.reason,
      licenseText: c.licenseText,
    })),
    apacheText: APACHE_TEXT,
  };

  return `// SPDX-License-Identifier: Apache-2.0
/**
 * GENERATED by \`bun run licenses\` — do not edit.
 *
 * Ruling 47: Apache-2.0 §4(a) is owed to whoever receives the binary, and under
 * ruling 26 that is often the binary alone. This module is how \`brigadier
 * licenses\` discharges it without a file beside the executable.
 */

export interface ThirdPartyComponent {
  name: string;
  version: string;
  license: string;
  copyright: string | null;
  reason: string;
  licenseText: string;
}

export interface LicenseManifest {
  self: { name: string; license: string; copyright: string };
  components: ThirdPartyComponent[];
  apacheText: string;
}

export const LICENSES: LicenseManifest = ${JSON.stringify(payload, null, 2)};
`;
}

const components = allComponents();

// The generator refuses to render a licence the gate would reject. Producing a
// tidy attribution file for a component that may not be redistributed would be
// the worst of both worlds: it documents the violation and looks like diligence.
const disallowed = components.filter((c) => c.origin === "npm" && !isAllowed(c.license));
if (disallowed.length > 0) {
  console.error("Refusing to generate attribution — these licences are outside the allowlist:");
  for (const c of disallowed) console.error(`  ${c.name}@${c.version}  ${c.license}`);
  console.error("\nSee ruling 47. Either the dependency goes, or the allowlist changes deliberately.");
  process.exit(1);
}

const markdown = renderMarkdown(components);
const typescript = renderTypeScript(components);

const markdownPath = join(REPO_ROOT, "THIRD-PARTY.md");
const typescriptPath = join(REPO_ROOT, "src", "generated", "licenses.ts");

if (Bun.argv.includes("--check")) {
  let stale = false;
  for (const [path, expected] of [
    [markdownPath, markdown],
    [typescriptPath, typescript],
  ] as const) {
    const actual = await Bun.file(path)
      .text()
      .catch(() => "");
    if (actual !== expected) {
      console.error(`STALE  ${path.replace(REPO_ROOT + "/", "")}`);
      stale = true;
    }
  }
  if (stale) {
    console.error("\nRun `bun run licenses`. The committed attribution disagrees with what is bundled.");
    process.exit(1);
  }
  console.log(`attribution current — ${components.length} component(s)`);
} else {
  mkdirSync(join(REPO_ROOT, "src", "generated"), { recursive: true });
  writeFileSync(markdownPath, markdown);
  writeFileSync(typescriptPath, typescript);
  console.log(`wrote THIRD-PARTY.md and src/generated/licenses.ts — ${components.length} component(s)`);
  for (const c of components) console.log(`  ${c.origin.padEnd(7)} ${c.name}@${c.version}  ${c.license}`);
}
